### ISSUE TITLE
These lines aren't converted to list items

### ISSUE THREAD

**Issue by leathersole** [Kuadrant/docs.kuadrant.io#113]
https://github.com/Kuadrant/docs.kuadrant.io/blob/f138351a0da60875ad1dec596a061227dae0fe85/0.7.0/kuadrant-operator/doc/auth/index.html#L4299-L4303

**Comment by leathersole** [comment]
@thomasmaas @guicassolato Thanks for fixing this issue.
After I compared [the doc](https://docs.kuadrant.io/0.7.0/kuadrant-operator/doc/auth/#overlapping-gateway-and-httproute-authpolicies) and [auth.md](https://github.com/Kuadrant/kuadrant-operator/blob/main/doc/auth.md), I found some other line items aren't converted on the doc site. It seems to be due to the fact that GitHub and MkDocs interpret markdown files differently. I'm going to create issues but you might want to review that difference in its entirety.

**Comment by thomasmaas** [comment]
Thank you @leathersole for noticing.

@guicassolato / @jasonmadigan any chance we can add something like https://github.com/adamb70/mdx-breakless-lists to have MkDocs behave the same as GitHub when it comes to not needing a white line before a list?

**Comment by jasonmadigan** [comment]
I spotted this a few weeks ago and meant to take a look at that same plugin. Thanks for the issue @leathersole
