### ISSUE TITLE
Cleanup root-level published docs

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/docs.kuadrant.io#122]
docs.kuadrant.io has a bunch of unversioned docs (from 0.6.x) at the root of the docs repo, which are referenced a couple of external places

We need to remove/clean these up:

- https://github.com/Kuadrant/docs.kuadrant.io/tree/gh-pages
- The only dirs that should remain should be dev, 0.6.1, 0.7.0 and the symlinks
- Find any broken, internal links in the docs that reference "root level" documents, and change their links:
  - e.g. abs links to `/getting-started-single-cluster/` should go to `/latest/getting-started-single-cluster/` (`latest` always refers to "latest stable"
  - Check kuadrant.io links to make sure they hit /latest/*

**Comment by jasonmadigan** [comment]
https://github.com/Kuadrant/kuadrant.github.io/pull/57

**Comment by ehearneRedHat** [comment]
@jasonmadigan broken link in `0.6.1` version of docs for endpoint `/0.6.1/multicluster-gateway-controller/docs/dnspolicy/dns-policy/` - returns `404` .

**Comment by jasonmadigan** [comment]
Merged
