### ISSUE TITLE
Authorino docs based on pretty old version

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/docs.kuadrant.io#136]
Latest version of the Kuadrant docs published to the website pulled a very old version of the Authorino docs.

The following user guide, for example:

<img width="1122" alt="Screenshot 2024-09-25 at 13 07 57" src="https://github.com/user-attachments/assets/10ca45da-015f-4b95-8a67-8e8055fb1528">

Looks different from the version available on GitHub:

<img width="1334" alt="Screenshot 2024-09-25 at 13 08 41" src="https://github.com/user-attachments/assets/f695c134-03b5-4d47-9558-7fb3b6536b32">

Maybe this has to do with the default `version` set to [`0.10.0`](https://github.com/Kuadrant/docs.kuadrant.io/commit/6030c290d59b83f81fb82954203f565968c57aca) incorrectly pulling v0.10.0 of Authorino:

<img width="1142" alt="Screenshot 2024-09-25 at 13 09 39" src="https://github.com/user-attachments/assets/2fa5c6cb-197e-43f8-ae24-53ed1c425fb2">

**Comment by jasonmadigan** [comment]
think https://github.com/Kuadrant/docs.kuadrant.io/blob/0.10.0/mkdocs.yml#L68C24-L68C97 should ref the `v0.18.0` tag. I'll patchup today

**Comment by jasonmadigan** [comment]
Fixed with https://github.com/Kuadrant/docs.kuadrant.io/commit/b805535a2341c88aaa85b1dadd9471ff2675e1ad
