### ISSUE TITLE
Define how to "freeze" a Kuadrant release

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/docs.kuadrant.io#42]
We need to define how we'd freeze the docs on some release of Kuadrant (and its sub-components).
Should the website support versioned docs? Only for Kuadrant? For every components? Only support latest, but of the "right" components?

**Comment by jasonmadigan** [comment]
Resolved previously with: https://github.com/Kuadrant/docs.kuadrant.io/pull/102
