### ISSUE TITLE
Support versioning of docs with each release

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/docs.kuadrant.io#45]
MKdocs has some support for versioning
https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

We should introduce versioning to our docs. However as part of this we may also need to ensure the right version of docs are being brought in from each of the different components

**Comment by jasonmadigan** [comment]
https://github.com/Kuadrant/docs.kuadrant.io/pull/102
